### ISSUE TITLE
Add Tunisian Ministry of Religious Affairs

### ISSUE THREAD

**Issue by spcbfr** [AhmedElywa/prayCalendar#1]
Hi, could you please add tunisia as a calculation method?

**Comment by AhmedElywa** [comment]
Sorry but the api we use don't support 

Only list 

0 - Shia Ithna-Ashari
1 - University of Islamic Sciences, Karachi
2 - Islamic Society of North America
3 - Muslim World League
4 - Umm Al-Qura University, Makkah
5 - Egyptian General Authority of Survey
7 - Institute of Geophysics, University of Tehran
8 - Gulf Region
9 - Kuwait
10 - Qatar
11 - Majlis Ugama Islam Singapura, Singapore
12 - Union Organization islamic de France
13 - Diyanet İşleri Başkanlığı, Turkey
14 - Spiritual Administration of Muslims of Russia
15 - Moonsighting Committee Worldwide (also requires shafaq parameter)
16 - Dubai (unofficial)

**Comment by AhmedElywa** [comment]
https://aladhan.com/prayer-times-api#GetMethods

**Comment by AhmedElywa** [comment]
@spcbfr We added the Tunisia to the methods

**Comment by spcbfr** [comment]
Thank You!
