### ISSUE TITLE
Delayed prayer times by 4 hours

### ISSUE THREAD

**Issue by Maxiwld** [AhmedElywa/prayCalendar#2]
Hello Ahmed,

I really like your project! Thanks a lot. When subscribing to the URL for Abu Dhabi I noticed that prayer times in outlook don't match the expected prayer times with a consistent lag of +4 hours. Could you help me troubleshoot this issue, perhaps?

**Correct prayer times**
![image](https://github.com/AhmedElywa/prayCalendar/assets/108991804/cd092879-9879-4322-a752-96ab369a2d5e)

**Result after subscribing** to https://pray.ahmedelywa.com/api/prayer-times.ics?address=Abu%20Dhabi&method=5&alarm=5&duration=25 
- Entered: "Abu Dhabi" in Address
- Selected: Moonsighting Committee Worldwide (also requires shafaq parameter)
I also tried other methods with the same result
![image](https://github.com/AhmedElywa/prayCalendar/assets/108991804/c52ceff8-2cfd-4183-8be1-1b89d53256cc)

Thanks in advance and best regards,
Max

**Comment by AhmedElywa** [comment]
The method is so important you use the Egyptian calculation you should use what is used in the UAE. I think it's Umm Alqura

![image](https://github.com/AhmedElywa/prayCalendar/assets/4535142/c843c9c9-38b7-420c-a721-8ff4c01f653a)

**Comment by AhmedElywa** [comment]
![image](https://github.com/AhmedElywa/prayCalendar/assets/4535142/280ddea4-c1b1-40b0-aec0-2faee42525ba)

**Comment by AhmedElywa** [comment]
We give you the time with UTC and your calender should convert it to your local time so your issue is coming from you calendar 
test it with another one
