### ISSUE TITLE
How to delete prayer time ?

### ISSUE THREAD

**Issue by mesalem1** [AhmedElywa/prayCalendar#3]
Hi Ahmed,

I imported prayer time and it's working perfectly. 

Unfortunately, all prayer time events are added to my work calendar, which makes all events mixed up together. 

Please, I need to know how to remove all the added prayer time events from my work calendar, so I can re-import it in new calendar. 

Thank You.

**Comment by AhmedElywa** [comment]
You should use subscription link to add to your calendar if you removed this subscription link it will be deleted but if you exported the events from the link as a file and you imported them to your calendar you should delete them manually

Second time please use the link as subscription link into your calendar
