### ISSUE TITLE
Eqama Time

### ISSUE THREAD

**Issue by abozaid-ibrahim** [AhmedElywa/prayCalendar#4]
انا بستخدم ده علشان انزل اصلى ف المسجد ومحدش يحجز اجتماع ف نفس الوقت .. المشكه اللى بتقابلنى .. ان الاقامه بتكون بعد ١٥ دقيقه تقريبا من االاذان.. لو تقدر تضيف delay field. بحيث ان اظبط الكاليندر ان الوقت اللى هنزل اصلى فيه محدش يحجز اجتماع.ه (بفرض ان اقرب منبه بيكون قبل الصلاه بخمس دقايق وفيه ١٥ دقيقه للاقامه ,, ١٠ دقائق للصلاه وعشر دقايق الطريق يبقا كدا دخلنا ف ٣٥ دقيقه.) انا عايز ابقا حاجز بالظبط ال ٣٠ دقيقه مش ساعه كامله... اتمنى الفكره تكون وصلت ..

**Comment by AhmedElywa** [comment]
الايفنت الواحده بتحجز ٢٥ دقيقه 

![image](https://github.com/user-attachments/assets/40b3fd86-1481-47fc-9de6-c5f5dd8ac051)

**Comment by abozaid-ibrahim** [comment]
<img width="805" alt="image" src="https://github.com/user-attachments/assets/d671ed1d-4ba2-4028-9c0e-d63b2a51f5bd">
I want to have access to the tune parameter

**Comment by AhmedElywa** [comment]
Ok i will add this for you

**Comment by AhmedElywa** [comment]
done on this commit https://github.com/AhmedElywa/prayCalendar/commit/66092d0c4b6ae2bdf541f997ac2acf771f03c584
